config/routes.rb
require 'api_constraints'

CityGemApi::Application.routes.draw do
  resources :sites
  root 'sites#index'

  match '*all' => 'application#cors', via: :options

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/site.rb
class Site < ApplicationRecord
end

app/controllers/api/v1/sites_controller_spec.rb
# test not working- come back to later
# require 'spec_helper'
#
# describe Api::V1::SitesController do
#
#   before(:each) { request.headers['Accept'] = "application/vnd.citygem.v1" }
#
#   describe "GET #show" do
#     before(:each) do
#       @site = FactoryGirl.create :site
#       get :show, id: @site.id, format: :json
#     end
#
#     it { should respond_with 200 }
#   end
#
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found
  respond_to :json

  def record_not_found
    render json: { :error => "Record Not Found" }, status: 404
  end

  def cors
      # blank section for CORR
      render :text => ''
  end

  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Origin, Content-Type, Accept, Authorization, Token'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  def cors_preflight_check
    if request.method == 'OPTIONS'
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version, Token'
      headers['Access-Control-Max-Age'] = '1728000'

      render :text => '', :content_type => 'text/plain'
    end
  end

end

app/controllers/sites_controller.rb
# serve up json in controller

class SitesController < ApplicationController
  rescue_from Exception, :with => :handle_500


  def handle_500
    render json: { :error => "Error" }, status: 500
  end

  # THIS WILL GET ALL POSTS
  # GET /sites
  def index
    @sites = Site.all
    render json: @sites
  end

  # THIS WILL SHOW ONE POST BASED ON PARAMS
  # GET /sites/1
  def show
    @site = Site.find(params[:id])
    render json: @site
  end

  # THIS WILL DELETE ONE POST
  def destroy
    Site.destroy(params[:id])
  end

  def create
    @site = Site.create(site_params)
    @site.save
  end

  def update
    @site = Site.find(params[:id])
    @site.update_attributes(site_params)
  end

  private

  def site_params
    params.require(:site).permit(:name, :description, :city, :state, :lat, :long, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CityGemApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sites/_form.html.erb
<%= form_for(site) do |f| %>
  <% if site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <%= f.text_area :photo %>
  </div>

  <div class="field">
    <%= f.label :lat %>
    <%= f.number_field :lat %>
  </div>

  <div class="field">
    <%= f.label :long %>
    <%= f.text_field :long %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>City</th>
      <th>State</th>
      <th>Photo</th>
      <th>Lat</th>
      <th>Long</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.name %></td>
        <td><%= site.description %></td>
        <td><%= site.city %></td>
        <td><%= site.state %></td>
        <td><%= site.photo %></td>
        <td><%= site.lat %></td>
        <td><%= site.long %></td>
        <td><%= link_to 'Show', site %></td>
        <td><%= link_to 'Edit', edit_site_path(site) %></td>
        <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @site.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @site.description %>
</p>

<p>
  <strong>City:</strong>
  <%= @site.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @site.state %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @site.photo %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @site.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @site.long %>
</p>

<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>